// Mock data for AML Audit Flow System

// Regulatory Documents with hierarchical structure
export const regulatoryDocuments = [
  {
    id: 'bsa',
    title: 'Bank Secrecy Act',
    jurisdiction: 'US',
    lastUpdated: '2023-12-15',
    aggregateScore: 87,
    clauses: [
      {
        id: 'bsa-1020-320-a-1',
        title: 'Transaction Monitoring Requirements',
        reference: 'BSA § 1020.320(a)(1)',
        text: 'Each bank shall establish and maintain procedures reasonably designed to monitor account activity for transactions that are inconsistent with the normal and expected activity of the account holder.',
        score: 94,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-01-15'
        },
        evidence: [
          { id: 'ev1', type: 'rule-performance', description: 'Large Cash Transaction Monitoring', quality: 'excellent' },
          { id: 'ev2', type: 'backtest-results', description: 'Q4 2023 Transaction Pattern Analysis', quality: 'good' },
          { id: 'ev3', type: 'audit-report', description: 'Internal Monitoring System Review', quality: 'excellent' }
        ],
        linkedRules: ['rule-1', 'rule-2', 'rule-3']
      },
      {
        id: 'bsa-1020-320-a-2',
        title: 'Alert Investigation Timeline',
        reference: 'BSA § 1020.320(a)(2)',
        text: 'Banks shall establish reasonable procedures to conduct timely investigations of alerts generated by their transaction monitoring systems, with documentation of investigation outcomes.',
        score: 67,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking'],
          customerType: ['individual', 'business'],
          riskLevel: 'medium',
          lastReviewed: '2024-01-10'
        },
        evidence: [
          { id: 'ev4', type: 'workflow-metrics', description: 'Alert Investigation SLA Tracking', quality: 'fair' },
          { id: 'ev5', type: 'process-documentation', description: 'Investigation Documentation Procedures', quality: 'good' }
        ],
        linkedRules: ['rule-4', 'rule-5']
      },
      {
        id: 'bsa-1020-320-b',
        title: 'Transaction Threshold Monitoring',
        reference: 'BSA § 1020.320(b)',
        text: 'Banks shall establish monitoring thresholds and parameters to identify transactions that warrant further investigation based on amount, frequency, and other risk factors.',
        score: 91,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-01-20'
        },
        evidence: [
          { id: 'ev6', type: 'rule-performance', description: 'Threshold Monitoring Rules', quality: 'excellent' },
          { id: 'ev7', type: 'backtest-results', description: 'Aggregation Logic Testing', quality: 'excellent' }
        ],
        linkedRules: ['rule-1', 'rule-6', 'rule-7']
      }
    ]
  },
  {
    id: 'patriot',
    title: 'USA PATRIOT Act',
    jurisdiction: 'US',
    lastUpdated: '2023-11-30',
    aggregateScore: 82,
    clauses: [
      {
        id: 'patriot-326-a',
        title: 'Enhanced Transaction Monitoring',
        reference: 'Section 326(a)',
        text: 'Financial institutions shall implement enhanced transaction monitoring procedures for higher-risk customers and transactions, with appropriate documentation and escalation procedures.',
        score: 89,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking'],
          customerType: ['individual', 'business'],
          riskLevel: 'high',
          lastReviewed: '2023-12-01'
        },
        evidence: [
          { id: 'ev8', type: 'policy-documentation', description: 'Enhanced Monitoring Policy and Procedures', quality: 'excellent' },
          { id: 'ev9', type: 'training-records', description: 'Staff Transaction Monitoring Training', quality: 'good' }
        ],
        linkedRules: ['rule-8', 'rule-9']
      },
      {
        id: 'patriot-326-b',
        title: 'Risk-Based Transaction Parameters',
        reference: 'Section 326(b)',
        text: 'Transaction monitoring systems must include risk-based parameters that account for customer profiles, geographic factors, and transaction patterns.',
        score: 75,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking'],
          customerType: ['individual'],
          riskLevel: 'medium',
          lastReviewed: '2023-11-15'
        },
        evidence: [
          { id: 'ev10', type: 'system-validation', description: 'Identity Verification System Audit', quality: 'fair' },
          { id: 'ev11', type: 'sample-testing', description: 'Customer Onboarding Sample Review', quality: 'good' }
        ],
        linkedRules: ['rule-9', 'rule-10']
      }
    ]
  },
  {
    id: 'finra',
    title: 'FinCEN Transaction Monitoring',
    jurisdiction: 'US',
    lastUpdated: '2024-01-31',
    aggregateScore: 76,
    clauses: [
      {
        id: 'finra-tm-001',
        title: 'Automated Transaction Monitoring',
        reference: 'FinCEN Guidance 2019-001',
        text: 'Financial institutions must implement automated transaction monitoring systems capable of identifying potentially suspicious patterns across multiple accounts and time periods.',
        score: 83,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'critical',
          lastReviewed: '2024-02-01'
        },
        evidence: [
          { id: 'ev12', type: 'system-performance', description: 'Transaction Monitoring System Metrics', quality: 'good' },
          { id: 'ev13', type: 'alert-analysis', description: 'Alert Quality Assessment Reports', quality: 'excellent' }
        ],
        linkedRules: ['rule-11', 'rule-12']
      }
    ]
  },
  {
    id: 'internal-tmp',
    title: 'Internal Transaction Monitoring Policy',
    jurisdiction: 'US',
    lastUpdated: '2024-02-15',
    aggregateScore: 91,
    clauses: [
      {
        id: 'tmp-001',
        title: 'Transaction Monitoring System Governance',
        reference: 'TMP-001',
        text: 'The Bank shall maintain a comprehensive transaction monitoring program with clearly defined governance structure, including regular model validation, parameter tuning, and performance assessment.',
        score: 88,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-02-01'
        },
        evidence: [
          { id: 'ev14', type: 'policy-documentation', description: 'TM System Governance Framework', quality: 'excellent' },
          { id: 'ev15', type: 'committee-minutes', description: 'Monthly Model Risk Committee Reviews', quality: 'good' }
        ],
        linkedRules: ['rule-1', 'rule-2', 'rule-3']
      },
      {
        id: 'tmp-002',
        title: 'Alert Prioritization and Escalation',
        reference: 'TMP-002',
        text: 'All transaction monitoring alerts shall be prioritized based on risk scoring and customer profiles, with high-risk alerts requiring investigation within 5 business days and escalation procedures for complex cases.',
        score: 93,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'critical',
          lastReviewed: '2024-01-30'
        },
        evidence: [
          { id: 'ev16', type: 'workflow-metrics', description: 'Alert Prioritization SLA Performance', quality: 'excellent' },
          { id: 'ev17', type: 'training-records', description: 'Analyst Escalation Training Completion', quality: 'good' }
        ],
        linkedRules: ['rule-4']
      },
      {
        id: 'tmp-003',
        title: 'Customer Risk Profiling for Monitoring',
        reference: 'TMP-003',
        text: 'Customer risk profiles shall be updated quarterly and integrated into transaction monitoring parameters to ensure appropriate detection sensitivity for different customer segments.',
        score: 92,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-01-25'
        },
        evidence: [
          { id: 'ev18', type: 'system-validation', description: 'Risk Profile Integration Testing', quality: 'excellent' },
          { id: 'ev19', type: 'data-quality', description: 'Customer Data Completeness Report', quality: 'fair' }
        ],
        linkedRules: ['rule-1', 'rule-2']
      }
    ]
  }
];

// Rule Performance Data
export const rules = [
  {
    id: 'rule-1',
    name: 'Large Cash Transaction Detection',
    category: 'Cash Monitoring',
    description: 'Detects cash transactions above regulatory thresholds',
    metadata: {
      jurisdiction: ['US'],
      productType: ['retail-banking', 'commercial-banking'],
      customerType: ['individual', 'business'],
      riskLevel: 'high'
    },
    performance: {
      alertsPerMonth: 2847,
      truePositiveRate: 23,
      alertsInvestigated: 656,
      coverage: 100,
      avgResolutionDays: 12,
      lastBacktest: '2024-01-15',
      backtestScore: 78
    },
    linkedClauses: ['bsa-1020-320-a-1', 'bsa-1020-320-b']
  },
  {
    id: 'rule-2',
    name: 'Structuring Pattern Analysis',
    category: 'Behavioral Analytics',
    description: 'Identifies potential structuring patterns in customer transactions',
    metadata: {
      jurisdiction: ['US'],
      productType: ['retail-banking'],
      customerType: ['individual', 'business'],
      riskLevel: 'high'
    },
    performance: {
      alertsPerMonth: 1203,
      truePositiveRate: 31,
      alertsInvestigated: 373,
      coverage: 95,
      avgResolutionDays: 15,
      lastBacktest: '2024-01-10',
      backtestScore: 85
    },
    linkedClauses: ['bsa-1020-320-a-1']
  },
  {
    id: 'rule-3',
    name: 'Cross-Border Wire Monitoring',
    category: 'Wire Transfer Monitoring',
    description: 'Monitors international wire transfers for suspicious patterns',
    metadata: {
      jurisdiction: ['US'],
      productType: ['retail-banking', 'commercial-banking'],
      customerType: ['individual', 'business', 'corporate'],
      riskLevel: 'high'
    },
    performance: {
      alertsPerMonth: 892,
      truePositiveRate: 18,
      alertsInvestigated: 161,
      coverage: 88,
      avgResolutionDays: 18,
      lastBacktest: '2024-01-05',
      backtestScore: 72
    },
    linkedClauses: ['bsa-1020-320-a-1']
  },
  {
    id: 'rule-4',
    name: 'Alert Investigation Workflow',
    category: 'Process Management',
    description: 'Manages alert investigation workflow and documentation requirements',
    metadata: {
      jurisdiction: ['US'],
      productType: ['retail-banking', 'commercial-banking'],
      customerType: ['individual', 'business'],
      riskLevel: 'medium'
    },
    performance: {
      alertsPerMonth: 0, // Process rule, not alert-generating
      truePositiveRate: 0,
      alertsInvestigated: 1190, // Total alerts processed
      coverage: 67, // SLA compliance
      avgResolutionDays: 18,
      lastBacktest: '2024-01-12',
      backtestScore: 67
    },
    linkedClauses: ['bsa-1020-320-a-2']
  }
];

// System Alerts
export const alerts = [
  {
    id: 'alert-1',
    type: 'performance-degradation',
    priority: 'high',
    title: 'Alert Investigation SLA Compliance Below Target',
    description: 'Average resolution time for alert investigations has increased to 18 days, exceeding the 15-day target',
    relatedClause: 'bsa-1020-320-a-2',
    relatedRule: 'rule-4',
    createdAt: '2024-01-28T10:30:00Z',
    status: 'active',
    impact: 'Risk of delayed transaction investigation and potential regulatory findings',
    recommendation: 'Consider adding analyst capacity or optimizing alert assignment workflow'
  },
  {
    id: 'alert-2',
    type: 'coverage-gap',
    priority: 'medium',
    title: 'High-Value Transfer Monitoring Gap Identified',
    description: 'No active rules configured for monitoring high-value transfers above $100K across different business days',
    relatedClause: 'bsa-1020-320-b',
    relatedRule: null,
    createdAt: '2024-01-27T14:15:00Z',
    status: 'active',
    impact: 'Potential gap in detecting structured high-value transactions',
    recommendation: 'Implement cross-day aggregation rules for large transfers'
  },
  {
    id: 'alert-3',
    type: 'ai-insight',
    priority: 'medium',
    title: 'Cross-Border Wire False Positive Rate Increasing',
    description: 'ML analysis detected 15% increase in false positives for international wire transfers over past 30 days',
    relatedClause: 'bsa-1020-320-a-1',
    relatedRule: 'rule-3',
    createdAt: '2024-01-26T09:45:00Z',
    status: 'investigating',
    impact: 'Analyst efficiency impact, potential alert fatigue',
    recommendation: 'Review wire transfer rule thresholds and geographic risk scoring'
  },
  {
    id: 'alert-4',
    type: 'regulatory-update',
    priority: 'low',
    title: 'FinCEN Guidance Update Applied',
    description: 'New transaction monitoring parameters applied based on FinCEN guidance update',
    relatedClause: 'finra-tm-001',
    relatedRule: 'rule-11',
    createdAt: '2024-01-31T16:20:00Z',
    status: 'resolved',
    impact: 'Enhanced detection capabilities for complex transaction patterns',
    recommendation: 'Monitor alert volume for next 30 days to validate new parameters'
  },
  {
    id: 'alert-5',
    type: 'policy-compliance',
    priority: 'medium',
    title: 'Customer Risk Profile Update Overdue',
    description: 'Quarterly risk profile updates are overdue for 847 high-risk commercial customers, affecting monitoring sensitivity',
    relatedClause: 'tmp-003',
    relatedRule: 'rule-1',
    createdAt: '2024-02-01T11:15:00Z',
    status: 'active',
    impact: 'Reduced monitoring effectiveness for high-risk customer segments',
    recommendation: 'Prioritize risk profile refresh for commercial banking customers above $5M assets'
  }
];

// Analyst Capacity Data
export const analystCapacity = {
  currentStaff: 8,
  currentCapacity: {
    alertsPerDay: 45,
    avgResolutionHours: 4.2,
    investigationThreshold: 50000, // $50k minimum investigation threshold
    monthlyAlertVolume: 4942,
    utilizationRate: 87
  },
  scenarios: {
    '-2': {
      staffCount: 6,
      alertsPerDay: 33,
      investigationThreshold: 100000, // Higher threshold due to reduced capacity
      utilizationRate: 95,
      additionalInvestigationsPerMonth: -94,
      description: 'Reduced capacity scenario'
    },
    '-1': {
      staffCount: 7,
      alertsPerDay: 39,
      investigationThreshold: 75000, // Higher threshold due to reduced capacity
      utilizationRate: 92,
      additionalInvestigationsPerMonth: -47,
      description: 'Slightly reduced capacity'
    },
    '+1': {
      staffCount: 9,
      alertsPerDay: 51,
      investigationThreshold: 10000, // Could investigate $10k+ transactions
      utilizationRate: 78,
      additionalInvestigationsPerMonth: 47,
      description: 'Additional analyst scenario'
    },
    '+2': {
      staffCount: 10,
      alertsPerDay: 57,
      investigationThreshold: 5000, // Even lower threshold with more capacity
      utilizationRate: 71,
      additionalInvestigationsPerMonth: 94,
      description: 'Expanded team scenario'
    }
  },
  performanceMetrics: {
    avgAlertsPerAnalyst: 618,
    avgInvestigationsPerAnalyst: 149,
    qualityScore: 84,
    timelyClosureRate: 92
  }
};

// Overall Compliance Score Calculation
export const complianceMetrics = {
  overallScore: 84,
  lastCalculated: '2024-02-01T08:00:00Z',
  components: {
    clauseCoverage: 89, // % of clauses with adequate rule coverage
    rulePerformance: 78, // Weighted average of rule performance scores
    evidenceQuality: 85, // Quality of supporting evidence/documentation
    timelyRemediation: 82 // Speed of addressing identified gaps
  },
  trend: {
    lastMonth: 87,
    twoMonthsAgo: 85,
    threeMonthsAgo: 83
  }
};

// Helper functions for data manipulation
export const getClausesByScore = (minScore = 0, maxScore = 100) => {
  return regulatoryDocuments
    .flatMap(doc => doc.clauses)
    .filter(clause => clause.score >= minScore && clause.score <= maxScore);
};

export const getClauseById = (clauseId) => {
  return regulatoryDocuments
    .flatMap(doc => doc.clauses)
    .find(clause => clause.id === clauseId);
};

export const getRuleById = (ruleId) => {
  return rules.find(rule => rule.id === ruleId);
};

export const getScoreClass = (score) => {
  if (score >= 90) return 'excellent';
  if (score >= 80) return 'good';
  if (score >= 70) return 'fair';
  if (score >= 60) return 'poor';
  return 'critical';
};

export const getScoreStyles = (score) => {
  if (score >= 90) return { backgroundColor: '#10b981', color: 'white' };
  if (score >= 80) return { backgroundColor: '#84cc16', color: 'white' };
  if (score >= 70) return { backgroundColor: '#f59e0b', color: 'white' };
  if (score >= 60) return { backgroundColor: '#ef4444', color: 'white' };
  return { backgroundColor: '#dc2626', color: 'white' };
};

export const getClauseScoreStyles = (score) => {
  if (score >= 90) return 'bg-green-50 border-l-4 border-l-green-500';
  if (score >= 80) return 'bg-lime-50 border-l-4 border-l-lime-500';
  if (score >= 70) return 'bg-amber-50 border-l-4 border-l-amber-500';
  if (score >= 60) return 'bg-red-50 border-l-4 border-l-red-500';
  return 'bg-red-100 border-l-4 border-l-red-600';
};