// Mock data for AML Audit Flow System

// Score conversion utility: Convert percentage (0-100) to 1-5 scale
const convertPercentageToFiveScale = (percentage) => {
  if (percentage >= 90) return 5;
  if (percentage >= 80) return 4;
  if (percentage >= 70) return 3;
  if (percentage >= 60) return 2;
  return 1;
};

// Data validation utilities
export const validateDocumentData = (documents) => {
  if (!Array.isArray(documents)) {
    throw new Error('Documents must be an array');
  }
  
  documents.forEach(doc => {
    if (!doc.id || !doc.title || !doc.clauses) {
      throw new Error(`Invalid document structure: ${doc.id || 'unknown'}`);
    }
    
    if (!Array.isArray(doc.clauses)) {
      throw new Error(`Document clauses must be an array: ${doc.id}`);
    }
    
    doc.clauses.forEach(clause => {
      if (!clause.id || !clause.title || !clause.metadata) {
        throw new Error(`Invalid clause structure: ${clause.id || 'unknown'}`);
      }
    });
  });
  
  return documents;
};

export const validateAlerts = (alerts) => {
  if (!Array.isArray(alerts)) {
    throw new Error('Alerts must be an array');
  }
  
  alerts.forEach(alert => {
    if (!alert.id || !alert.type || !alert.priority) {
      throw new Error(`Invalid alert structure: ${alert.id || 'unknown'}`);
    }
  });
  
  return alerts;
};

// Regulatory Documents with hierarchical structure
export const regulatoryDocuments = [
  {
    id: 'bsa',
    title: 'Bank Secrecy Act',
    jurisdiction: 'US',
    lastUpdated: '2023-12-15',
    aggregateScore: 4,
    clauses: [
      {
        id: 'bsa-1020-320-a-1',
        title: 'Transaction Monitoring Requirements',
        reference: 'BSA § 1020.320(a)(1)',
        text: 'Each bank shall establish and maintain procedures reasonably designed to monitor account activity for transactions that are inconsistent with the normal and expected activity of the account holder.',
        score: 3,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-01-15'
        },
        evidence: [
          { id: 'ev1', type: 'rule-performance', description: 'Large Cash Transaction Monitoring', quality: 'excellent' },
          { id: 'ev2', type: 'backtest-results', description: 'Q4 2023 Transaction Pattern Analysis', quality: 'good' },
          { id: 'ev3', type: 'audit-report', description: 'Internal Monitoring System Review', quality: 'excellent' }
        ],
        linkedRules: ['rule-1', 'rule-2', 'rule-3']
      },
      {
        id: 'bsa-1020-320-a-2',
        title: 'Alert Investigation Timeline',
        reference: 'BSA § 1020.320(a)(2)',
        text: 'Banks shall establish reasonable procedures to conduct timely investigations of alerts generated by their transaction monitoring systems, with documentation of investigation outcomes.',
        score: 2,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking'],
          customerType: ['individual', 'business'],
          riskLevel: 'medium',
          lastReviewed: '2024-01-10'
        },
        evidence: [
          { id: 'ev4', type: 'workflow-metrics', description: 'Alert Investigation SLA Tracking', quality: 'fair' },
          { id: 'ev5', type: 'process-documentation', description: 'Investigation Documentation Procedures', quality: 'good' }
        ],
        linkedRules: ['rule-4', 'rule-5']
      },
      {
        id: 'bsa-1020-320-b',
        title: 'Transaction Threshold Monitoring',
        reference: 'BSA § 1020.320(b)',
        text: 'Banks shall establish monitoring thresholds and parameters to identify transactions that warrant further investigation based on amount, frequency, and other risk factors.',
        score: 3,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-01-20'
        },
        evidence: [
          { id: 'ev6', type: 'rule-performance', description: 'Threshold Monitoring Rules', quality: 'excellent' },
          { id: 'ev7', type: 'backtest-results', description: 'Aggregation Logic Testing', quality: 'excellent' }
        ],
        linkedRules: ['rule-1', 'rule-6', 'rule-7']
      }
    ]
  },
  {
    id: 'patriot',
    title: 'USA PATRIOT Act',
    jurisdiction: 'US',
    lastUpdated: '2023-11-30',
    aggregateScore: 4,
    clauses: [
      {
        id: 'patriot-326-a',
        title: 'Enhanced Transaction Monitoring',
        reference: 'Section 326(a)',
        text: 'Financial institutions shall implement enhanced transaction monitoring procedures for higher-risk customers and transactions, with appropriate documentation and escalation procedures.',
        score: 4,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking'],
          customerType: ['individual', 'business'],
          riskLevel: 'high',
          lastReviewed: '2023-12-01'
        },
        evidence: [
          { id: 'ev8', type: 'policy-documentation', description: 'Enhanced Monitoring Policy and Procedures', quality: 'excellent' },
          { id: 'ev9', type: 'training-records', description: 'Staff Transaction Monitoring Training', quality: 'good' }
        ],
        linkedRules: ['rule-8', 'rule-9']
      },
      {
        id: 'patriot-326-b',
        title: 'Risk-Based Transaction Parameters',
        reference: 'Section 326(b)',
        text: 'Transaction monitoring systems must include risk-based parameters that account for customer profiles, geographic factors, and transaction patterns.',
        score: 3,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking'],
          customerType: ['individual'],
          riskLevel: 'medium',
          lastReviewed: '2023-11-15'
        },
        evidence: [
          { id: 'ev10', type: 'system-validation', description: 'Identity Verification System Audit', quality: 'fair' },
          { id: 'ev11', type: 'sample-testing', description: 'Customer Onboarding Sample Review', quality: 'good' }
        ],
        linkedRules: ['rule-9', 'rule-10']
      }
    ]
  },
  {
    id: 'finra',
    title: 'FinCEN Transaction Monitoring',
    jurisdiction: 'US',
    lastUpdated: '2024-01-31',
    aggregateScore: 3,
    clauses: [
      {
        id: 'finra-tm-001',
        title: 'Automated Transaction Monitoring',
        reference: 'FinCEN Guidance 2019-001',
        text: 'Financial institutions must implement automated transaction monitoring systems capable of identifying potentially suspicious patterns across multiple accounts and time periods.',
        score: 4,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'critical',
          lastReviewed: '2024-02-01'
        },
        evidence: [
          { id: 'ev12', type: 'system-performance', description: 'Transaction Monitoring System Metrics', quality: 'good' },
          { id: 'ev13', type: 'alert-analysis', description: 'Alert Quality Assessment Reports', quality: 'excellent' }
        ],
        linkedRules: ['rule-11', 'rule-12']
      }
    ]
  },
  {
    id: 'internal-tmp',
    title: 'Internal Transaction Monitoring Policy',
    jurisdiction: 'US',
    lastUpdated: '2024-02-15',
    aggregateScore: 5,
    clauses: [
      {
        id: 'tmp-001',
        title: 'Transaction Monitoring System Governance',
        reference: 'TMP-001',
        text: 'The Bank shall maintain a comprehensive transaction monitoring program with clearly defined governance structure, including regular model validation, parameter tuning, and performance assessment.',
        score: 4,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-02-01'
        },
        evidence: [
          { id: 'ev14', type: 'policy-documentation', description: 'TM System Governance Framework', quality: 'excellent' },
          { id: 'ev15', type: 'committee-minutes', description: 'Monthly Model Risk Committee Reviews', quality: 'good' }
        ],
        linkedRules: ['rule-1', 'rule-2', 'rule-3']
      },
      {
        id: 'tmp-002',
        title: 'Alert Prioritization and Escalation',
        reference: 'TMP-002',
        text: 'All transaction monitoring alerts shall be prioritized based on risk scoring and customer profiles, with high-risk alerts requiring investigation within 5 business days and escalation procedures for complex cases.',
        score: 5,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'critical',
          lastReviewed: '2024-01-30'
        },
        evidence: [
          { id: 'ev16', type: 'workflow-metrics', description: 'Alert Prioritization SLA Performance', quality: 'excellent' },
          { id: 'ev17', type: 'training-records', description: 'Analyst Escalation Training Completion', quality: 'good' }
        ],
        linkedRules: ['rule-4']
      },
      {
        id: 'tmp-003',
        title: 'Customer Risk Profiling for Monitoring',
        reference: 'TMP-003',
        text: 'Customer risk profiles shall be updated quarterly and integrated into transaction monitoring parameters to ensure appropriate detection sensitivity for different customer segments.',
        score: 5,
        metadata: {
          jurisdiction: ['US'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-01-25'
        },
        evidence: [
          { id: 'ev18', type: 'system-validation', description: 'Risk Profile Integration Testing', quality: 'excellent' },
          { id: 'ev19', type: 'data-quality', description: 'Customer Data Completeness Report', quality: 'fair' }
        ],
        linkedRules: ['rule-1', 'rule-2']
      }
    ]
  },
  {
    id: 'uk-money-laundering-regs',
    title: 'UK Money Laundering Regulations 2017',
    jurisdiction: 'UK',
    lastUpdated: '2023-10-15',
    aggregateScore: 5,
    clauses: [
      {
        id: 'uk-mlr-2017-reg-28',
        title: 'Ongoing Transaction Monitoring',
        reference: 'MLR 2017 Regulation 28',
        text: 'Relevant persons must conduct ongoing monitoring of their business relationship with a customer, including scrutiny of transactions undertaken throughout the course of that relationship to ensure that the transactions being conducted are consistent with the person\'s knowledge of the customer, their business and risk profile.',
        score: 5,
        metadata: {
          jurisdiction: ['UK'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-01-18'
        },
        evidence: [
          { id: 'ev20', type: 'rule-performance', description: 'UK Transaction Pattern Analysis', quality: 'excellent' },
          { id: 'ev21', type: 'backtest-results', description: 'Cross-Border Transaction Monitoring', quality: 'good' },
          { id: 'ev22', type: 'policy-documentation', description: 'UK Regulatory Compliance Procedures', quality: 'excellent' }
        ],
        linkedRules: ['rule-1', 'rule-2', 'rule-8']
      },
      {
        id: 'uk-mlr-2017-reg-19',
        title: 'Enhanced Due Diligence - High Risk Transactions',
        reference: 'MLR 2017 Regulation 19',
        text: 'Where relevant persons identify higher risk transactions or business relationships, they must conduct enhanced due diligence measures including enhanced ongoing monitoring to determine whether transactions are unusual or potentially suspicious.',
        score: 5,
        metadata: {
          jurisdiction: ['UK'],
          productType: ['wealth-management', 'commercial-banking'],
          customerType: ['business', 'corporate'],
          riskLevel: 'critical',
          lastReviewed: '2024-01-22'
        },
        evidence: [
          { id: 'ev23', type: 'enhanced-monitoring', description: 'High-Risk Customer Screening Process', quality: 'excellent' },
          { id: 'ev24', type: 'audit-report', description: 'FCA Compliance Assessment 2023', quality: 'excellent' }
        ],
        linkedRules: ['rule-9', 'rule-10']
      },
      {
        id: 'uk-proceeds-crime-act-s330',
        title: 'Suspicious Activity Reporting Requirements', 
        reference: 'POCA 2002 Section 330',
        text: 'A person commits an offence if each of the following conditions is satisfied: they know or suspect that another person is engaged in money laundering, the information came to them in the course of business in the regulated sector, and they do not make the required disclosure as soon as is reasonably practicable after the information comes to them.',
        score: 4,
        metadata: {
          jurisdiction: ['UK'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-01-15'
        },
        evidence: [
          { id: 'ev25', type: 'sar-metrics', description: 'Suspicious Activity Report Filing Statistics', quality: 'good' },
          { id: 'ev26', type: 'training-records', description: 'UK SAR Filing Training Completion', quality: 'fair' }
        ],
        linkedRules: ['rule-4', 'rule-5', 'rule-11']
      }
    ]
  },
  {
    id: 'eu-aml-directive',
    title: 'EU Anti-Money Laundering Directive (AMLD5)',
    jurisdiction: 'EU',
    lastUpdated: '2023-11-28',
    aggregateScore: 4,
    clauses: [
      {
        id: 'eu-amld5-art13',
        title: 'Ongoing Customer Due Diligence and Monitoring',
        reference: 'AMLD5 Article 13',
        text: 'Obliged entities shall conduct ongoing monitoring of the business relationship including scrutiny of transactions undertaken throughout the course of that relationship to ensure that the transactions being conducted are consistent with their knowledge of the customer, their business and risk profile.',
        score: 4,
        metadata: {
          jurisdiction: ['EU'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-01-20'
        },
        evidence: [
          { id: 'ev27', type: 'rule-performance', description: 'EU Cross-Border Transaction Analysis', quality: 'excellent' },
          { id: 'ev28', type: 'regulatory-mapping', description: 'AMLD5 Compliance Framework', quality: 'excellent' },
          { id: 'ev29', type: 'backtest-results', description: 'EU Payment Pattern Recognition', quality: 'good' }
        ],
        linkedRules: ['rule-1', 'rule-6', 'rule-12']
      },
      {
        id: 'eu-amld5-art18a',
        title: 'Enhanced Due Diligence for High-Risk Third Countries',
        reference: 'AMLD5 Article 18a',
        text: 'Member States shall require obliged entities to apply enhanced due diligence measures when dealing with natural persons or legal entities established in high-risk third countries identified by the Commission, including enhanced ongoing monitoring.',
        score: 4,
        metadata: {
          jurisdiction: ['EU'],
          productType: ['commercial-banking', 'wealth-management'],
          customerType: ['business', 'corporate'],
          riskLevel: 'critical',
          lastReviewed: '2024-01-25'
        },
        evidence: [
          { id: 'ev30', type: 'geographic-screening', description: 'High-Risk Country Monitoring Rules', quality: 'excellent' },
          { id: 'ev31', type: 'policy-documentation', description: 'EU Enhanced Due Diligence Procedures', quality: 'good' }
        ],
        linkedRules: ['rule-9', 'rule-12']
      },
      {
        id: 'eu-amld5-art33',
        title: 'Reporting of Suspicious Transactions',
        reference: 'AMLD5 Article 33',
        text: 'Member States shall require obliged entities to promptly inform the financial intelligence unit when they know, suspect or have reasonable grounds to suspect that funds, regardless of the amount involved, are the proceeds of criminal activity or are related to terrorist financing.',
        score: 3,
        metadata: {
          jurisdiction: ['EU'],
          productType: ['retail-banking', 'commercial-banking', 'wealth-management'],
          customerType: ['individual', 'business', 'corporate'],
          riskLevel: 'high',
          lastReviewed: '2024-01-12'
        },
        evidence: [
          { id: 'ev32', type: 'str-metrics', description: 'Suspicious Transaction Report Statistics', quality: 'fair' },
          { id: 'ev33', type: 'workflow-documentation', description: 'EU STR Filing Process Documentation', quality: 'good' }
        ],
        linkedRules: ['rule-4', 'rule-5']
      }
    ]
  }
];

// Rule Performance Data
export const rules = [
  {
    id: 'rule-1',
    name: 'Large Cash Transaction Detection',
    category: 'Cash Monitoring',
    description: 'Detects cash transactions above regulatory thresholds',
    metadata: {
      jurisdiction: ['US'],
      productType: ['retail-banking', 'commercial-banking'],
      customerType: ['individual', 'business'],
      riskLevel: 'high'
    },
    performance: {
      alertsPerMonth: 2847,
      truePositiveRate: 23,
      alertsInvestigated: 656,
      coverage: 5,
      avgResolutionDays: 12,
      lastBacktest: '2024-01-15',
      backtestScore: 3
    },
    linkedClauses: ['bsa-1020-320-a-1', 'bsa-1020-320-b']
  },
  {
    id: 'rule-2',
    name: 'Structuring Pattern Analysis',
    category: 'Behavioral Analytics',
    description: 'Identifies potential structuring patterns in customer transactions',
    metadata: {
      jurisdiction: ['US'],
      productType: ['retail-banking'],
      customerType: ['individual', 'business'],
      riskLevel: 'high'
    },
    performance: {
      alertsPerMonth: 1203,
      truePositiveRate: 31,
      alertsInvestigated: 373,
      coverage: 5,
      avgResolutionDays: 15,
      lastBacktest: '2024-01-10',
      backtestScore: 4
    },
    linkedClauses: ['bsa-1020-320-a-1']
  },
  {
    id: 'rule-3',
    name: 'Cross-Border Wire Monitoring',
    category: 'Wire Transfer Monitoring',
    description: 'Monitors international wire transfers for suspicious patterns',
    metadata: {
      jurisdiction: ['US'],
      productType: ['retail-banking', 'commercial-banking'],
      customerType: ['individual', 'business', 'corporate'],
      riskLevel: 'high'
    },
    performance: {
      alertsPerMonth: 892,
      truePositiveRate: 18,
      alertsInvestigated: 161,
      coverage: 4,
      avgResolutionDays: 18,
      lastBacktest: '2024-01-05',
      backtestScore: 3
    },
    linkedClauses: ['bsa-1020-320-a-1']
  },
  {
    id: 'rule-4',
    name: 'Alert Investigation Workflow',
    category: 'Process Management',
    description: 'Manages alert investigation workflow and documentation requirements',
    metadata: {
      jurisdiction: ['US'],
      productType: ['retail-banking', 'commercial-banking'],
      customerType: ['individual', 'business'],
      riskLevel: 'medium'
    },
    performance: {
      alertsPerMonth: 0, // Process rule, not alert-generating
      truePositiveRate: 0,
      alertsInvestigated: 1190, // Total alerts processed
      coverage: 2, // SLA compliance
      avgResolutionDays: 18,
      lastBacktest: '2024-01-12',
      backtestScore: 2
    },
    linkedClauses: ['bsa-1020-320-a-2']
  },
  {
    id: 'rule-8',
    name: 'UK Enhanced Transaction Monitoring',
    description: 'Monitors high-value and cross-border transactions for UK regulatory compliance',
    category: 'Geographic Risk Monitoring',
    status: 'active',
    performance: {
      alertsPerMonth: 145,
      truePositiveRate: 24,
      alertsInvestigated: 145,
      coverage: 5,
      lastBacktest: '2024-01-20',
      backtestScore: 5
    },
    linkedClauses: ['uk-mlr-2017-reg-28', 'uk-mlr-2017-reg-19']
  },
  {
    id: 'rule-9', 
    name: 'Enhanced Due Diligence Monitoring',
    description: 'Automated monitoring for high-risk customers requiring enhanced due diligence procedures',
    category: 'Risk-Based Monitoring',
    status: 'active',
    performance: {
      alertsPerMonth: 78,
      truePositiveRate: 35,
      alertsInvestigated: 78,
      coverage: 5,
      lastBacktest: '2024-01-25',
      backtestScore: 4
    },
    linkedClauses: ['uk-mlr-2017-reg-19', 'eu-amld5-art18a']
  },
  {
    id: 'rule-10',
    name: 'UK High-Risk Relationship Monitoring', 
    description: 'Continuous monitoring of politically exposed persons and high-risk business relationships',
    category: 'PEP and High-Risk Monitoring',
    status: 'active',
    performance: {
      alertsPerMonth: 34,
      truePositiveRate: 42,
      alertsInvestigated: 34,
      coverage: 4,
      lastBacktest: '2024-01-15',
      backtestScore: 5
    },
    linkedClauses: ['uk-mlr-2017-reg-19']
  },
  {
    id: 'rule-11',
    name: 'UK SAR Filing Compliance Monitor',
    description: 'Monitors compliance with UK suspicious activity reporting requirements and timelines',
    category: 'Regulatory Reporting',
    status: 'active', 
    performance: {
      alertsPerMonth: 23,
      truePositiveRate: 24,
      alertsInvestigated: 23,
      coverage: 5,
      lastBacktest: '2024-01-18',
      backtestScore: 4
    },
    linkedClauses: ['uk-proceeds-crime-act-s330']
  },
  {
    id: 'rule-12',
    name: 'EU Cross-Border Transaction Analysis',
    description: 'Monitors transactions involving EU high-risk third countries and cross-border patterns',
    category: 'Geographic Risk Monitoring',
    status: 'active',
    performance: {
      alertsPerMonth: 189,
      truePositiveRate: 24,
      alertsInvestigated: 189,
      coverage: 5,
      lastBacktest: '2024-01-22',
      backtestScore: 4
    },
    linkedClauses: ['eu-amld5-art13', 'eu-amld5-art18a']
  }
];

// System Alerts
export const alerts = [
  {
    id: 'alert-1',
    type: 'performance-degradation',
    priority: 'high',
    title: 'Alert Investigation SLA Compliance Below Target',
    description: 'Average resolution time for alert investigations has increased to 18 days, exceeding the 15-day target',
    relatedClause: 'bsa-1020-320-a-2',
    relatedRule: 'rule-4',
    createdAt: '2024-01-28T10:30:00Z',
    status: 'active',
    impact: 'Risk of delayed transaction investigation and potential regulatory findings',
    recommendation: 'Consider adding analyst capacity or optimizing alert assignment workflow'
  },
  {
    id: 'alert-2',
    type: 'coverage-gap',
    priority: 'medium',
    title: 'High-Value Transfer Monitoring Gap Identified',
    description: 'No active rules configured for monitoring high-value transfers above $100K across different business days',
    relatedClause: 'bsa-1020-320-b',
    relatedRule: null,
    createdAt: '2024-01-27T14:15:00Z',
    status: 'active',
    impact: 'Potential gap in detecting structured high-value transactions',
    recommendation: 'Implement cross-day aggregation rules for large transfers'
  },
  {
    id: 'alert-3',
    type: 'ai-insight',
    priority: 'medium',
    title: 'Cross-Border Wire False Positive Rate Increasing',
    description: 'ML analysis detected 15% increase in false positives for international wire transfers over past 30 days',
    relatedClause: 'bsa-1020-320-a-1',
    relatedRule: 'rule-3',
    createdAt: '2024-01-26T09:45:00Z',
    status: 'investigating',
    impact: 'Analyst efficiency impact, potential alert fatigue',
    recommendation: 'Review wire transfer rule thresholds and geographic risk scoring'
  },
  {
    id: 'alert-4',
    type: 'regulatory-update',
    priority: 'low',
    title: 'FinCEN Guidance Update Applied',
    description: 'New transaction monitoring parameters applied based on FinCEN guidance update',
    relatedClause: 'finra-tm-001',
    relatedRule: 'rule-11',
    createdAt: '2024-01-31T16:20:00Z',
    status: 'resolved',
    impact: 'Enhanced detection capabilities for complex transaction patterns',
    recommendation: 'Monitor alert volume for next 30 days to validate new parameters'
  },
  {
    id: 'alert-5',
    type: 'policy-compliance',
    priority: 'medium',
    title: 'Customer Risk Profile Update Overdue',
    description: 'Quarterly risk profile updates are overdue for 847 high-risk commercial customers, affecting monitoring sensitivity',
    relatedClause: 'tmp-003',
    relatedRule: 'rule-1',
    createdAt: '2024-02-01T11:15:00Z',
    status: 'active',
    impact: 'Reduced monitoring effectiveness for high-risk customer segments',
    recommendation: 'Prioritize risk profile refresh for commercial banking customers above $5M assets'
  },
  {
    id: 'alert-6',
    type: 'regulatory-compliance',
    priority: 'high',
    title: 'UK MLR 2017 Enhanced Due Diligence Coverage Gap',
    description: 'Enhanced due diligence monitoring coverage for UK high-risk customers has dropped to 89%, below the 95% target required by MLR 2017',
    relatedClause: 'uk-mlr-2017-reg-19',
    relatedRule: 'rule-9',
    createdAt: '2024-01-29T08:20:00Z',
    status: 'active',
    impact: 'Potential regulatory compliance risk for UK FCA supervision',
    recommendation: 'Review customer risk classification and enhance automated screening for UK high-risk segments'
  },
  {
    id: 'alert-7',
    type: 'performance-degradation',
    priority: 'medium', 
    title: 'EU Cross-Border Transaction False Positives Rising',
    description: 'EU cross-border transaction monitoring showing 24% increase in false positives over past 45 days, impacting analyst efficiency',
    relatedClause: 'eu-amld5-art13',
    relatedRule: 'rule-12',
    createdAt: '2024-01-27T16:45:00Z',
    status: 'investigating',
    impact: 'Analyst capacity strain and potential delay in genuine suspicious activity detection',
    recommendation: 'Calibrate EU geographic risk scoring parameters and review third-country classifications'
  },
  {
    id: 'alert-8',
    type: 'coverage-gap',
    priority: 'high',
    title: 'AMLD5 High-Risk Third Country Monitoring Incomplete',
    description: 'Monitoring coverage for transactions with EU-designated high-risk third countries only covers 73% of applicable customer base',
    relatedClause: 'eu-amld5-art18a',
    relatedRule: 'rule-12',
    createdAt: '2024-01-30T12:30:00Z',
    status: 'active',
    impact: 'Non-compliance risk with AMLD5 enhanced due diligence requirements',
    recommendation: 'Expand customer segmentation to include all EU high-risk third country exposure'
  }
];

// Analyst Capacity Data
export const analystCapacity = {
  currentStaff: 8,
  currentCapacity: {
    alertsPerDay: 45,
    avgResolutionHours: 4.2,
    investigationThreshold: 50000, // $50k minimum investigation threshold
    monthlyAlertVolume: 4942,
    utilizationRate: 4
  },
  scenarios: {
    '-2': {
      staffCount: 6,
      alertsPerDay: 33,
      investigationThreshold: 100000, // Higher threshold due to reduced capacity
      utilizationRate: 5,
      additionalInvestigationsPerMonth: -94,
      description: 'Reduced capacity scenario'
    },
    '-1': {
      staffCount: 7,
      alertsPerDay: 39,
      investigationThreshold: 75000, // Higher threshold due to reduced capacity
      utilizationRate: 5,
      additionalInvestigationsPerMonth: -47,
      description: 'Slightly reduced capacity'
    },
    '+1': {
      staffCount: 9,
      alertsPerDay: 51,
      investigationThreshold: 10000, // Could investigate $10k+ transactions
      utilizationRate: 3,
      additionalInvestigationsPerMonth: 47,
      description: 'Additional analyst scenario'
    },
    '+2': {
      staffCount: 10,
      alertsPerDay: 57,
      investigationThreshold: 5000, // Even lower threshold with more capacity
      utilizationRate: 3,
      additionalInvestigationsPerMonth: 94,
      description: 'Expanded team scenario'
    }
  },
  performanceMetrics: {
    avgAlertsPerAnalyst: 618,
    avgInvestigationsPerAnalyst: 149,
    qualityScore: 4,
    timelyClosureRate: 5
  }
};

// Overall Compliance Score Calculation
export const complianceMetrics = {
  overallScore: 4,
  lastCalculated: '2024-02-01T08:00:00Z',
  components: {
    clauseCoverage: 4, // Score of clauses with adequate rule coverage
    rulePerformance: 3, // Weighted average of rule performance scores
    evidenceQuality: 4, // Quality of supporting evidence/documentation
    timelyRemediation: 4 // Speed of addressing identified gaps
  },
  trend: {
    lastMonth: 4,
    twoMonthsAgo: 4,
    threeMonthsAgo: 4
  }
};

// Helper functions for data manipulation
export const getClausesByScore = (minScore = 1, maxScore = 5) => {
  return regulatoryDocuments
    .flatMap(doc => doc.clauses)
    .filter(clause => clause.score >= minScore && clause.score <= maxScore);
};

export const getClauseById = (clauseId) => {
  return regulatoryDocuments
    .flatMap(doc => doc.clauses)
    .find(clause => clause.id === clauseId);
};

export const getRuleById = (ruleId) => {
  return rules.find(rule => rule.id === ruleId);
};

export const getScoreClass = (score) => {
  if (score === 5) return 'excellent';
  if (score === 4) return 'good';
  if (score === 3) return 'fair';
  if (score === 2) return 'poor';
  return 'critical';
};

// Standardized score styling utilities - all use CSS classes for consistency
export const getScoreStyles = (score) => {
  // Return CSS class names instead of inline styles for consistency
  const scoreClass = getScoreClass(score);
  return `score-${scoreClass}`;
};

export const getClauseScoreStyles = (score) => {
  const scoreClass = getScoreClass(score);
  return `clause-score-${scoreClass}`;
};

// Progress bar color utility for consistent coverage displays
export const getProgressBarClass = (score) => {
  if (score === 5) return 'bg-green-500';
  if (score === 4) return 'bg-lime-500'; 
  if (score === 3) return 'bg-amber-500';
  if (score === 2) return 'bg-red-500';
  return 'bg-red-600';
};

// Validate data on module load to catch issues early
try {
  validateDocumentData(regulatoryDocuments);
  validateAlerts(alerts);
  console.log('✅ Mock data validation passed');
} catch (error) {
  console.error('❌ Mock data validation failed:', error);
  throw error;
}